
name: Deploy to GCP
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to gcp
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo fagkveld-feb-2020
      uses: actions/checkout@master
    - uses: actions-hub/gcloud@master
      env:
        TEST: "whatsup"
        PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gsutil
      with:
        args: cp $TEST gs://bucket_fagkveld
