
name: Deploy to GCP
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to gcp
    runs-on: ubuntu-latest
    steps:
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ringed-subject-268309
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gsutil
      with:
        args: cp index.html gs://bucket_fagkveld
