name: Deploy event

on:
  repository_dispatch:
    types: deploy

jobs:
  deploy:
    name: Deploy to gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo fagkveld-feb-2020
        uses: actions/checkout@master
      - shell: bash
        run: |
          ${{ github.event.client_payload }} > dispatched.txt
      - uses: actions-hub/gcloud@master
        name: Deploy to GCP
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gsutil
        with:
          args: cp dispatched.txt gs://bucket_fagkveld